services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mytube-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mytube-db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mytube-frontend
    restart: always
    ports:
      - "3000:80"  # React через nginx обычно работает на 80

  db:
    image: postgres:16
    container_name: mytube-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4.5-alpine
    container_name: mytube-redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  minio:
    image: minio/minio
    container_name: mytube-minio
    ports:
      - "9000:9000"  # API
    volumes:
      - minio_data:/data
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data
    restart: always

volumes:
  db_data:
  minio_data:
